### ISSUE TITLE
Can this be done on mac?

### ISSUE THREAD

**Issue by appark** [raushel/tesla_wrappers#1]

**Comment by raushel** [comment]
Not sure, but might be possible: https://wilsonmar.github.io/powershell-on-mac/

**Comment by raushel** [comment]
Had another user report they were able to successfully use the scripts for tesla_dashcam / StitchTeslaCam.ps1 after installing PowerShell on Mac using the above guide to install. Would also need to install Python for Mac / ffmpeg.

Would need a replacement for Task Scheduler to run on a scheduler.

**Comment by raushel** [comment]
Added additional support for the change in slashes used in file paths. / vs \, etc

**Comment by appark** [comment]
any change you help me connect with user that did this on a mac?

**Comment by raushel** [comment]
Zog#8729 on the marcone teslausb discord: https://discord.gg/b4MHf2x
